name: stylix_ui
description: A semantic Flutter design system with customizable themes, brand presets, typography, and reusable UI components.
version: 1.0.3
repository: https://github.com/raouf-elmeddah/stylix_ui
topics:
  - flutter
  - design-system
  - theme
  - material3
  - design-tokens

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0



